#!/bin/bash

set -euxo pipefail

# kill background processes on exit.'
# see https://spin.atomicobject.com/2017/08/24/start-stop-bash-background-process/
trap "kill 0" EXIT

# start backend
go build -o dist/main fillorbust/api/main.go
./dist/main &

# rebuild frontend and run app
npx webpack && npm start &

wait